version: '3.8'
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/www/cdn/learnery-cdn/static:/app/static/outputPDF
    ports:
      - '7008:${PORT}'
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:7008/health']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
#    volumes:
#      - ./temp:/app
