### Cors-I

OPTIONS /auth/signin
Origin: https://creator-learnery-git-api-william-laciferin.vercel.app
Host: {{u}}
Access-Control-Request-Method: GET
Access-Control-Request-Headers: content-type


### Enable Cors Origin

OPTIONS {{u}}

### Enable Cors

OPTIONS /
Origin: https://vercel.app
Host: {{u}}
Access-Control-Request-Method: GET
Access-Control-Request-Headers: content-type
Access-Control-Allow-Credentials: true

### Enable Cors

OPTIONS /
Origin: http://localhost
Host: {{u}}
Access-Control-Request-Method: GET
Access-Control-Request-Headers: content-type

###  Cors: Fail

OPTIONS /
Origin: https://www.google.com
Host: {{u}}
Access-Control-Request-Method: GET
Access-Control-Request-Headers: content-type

### Home
GET {{u}}

### Health
GET {{u}}/health
Accept: application/json


### Signin
POST {{u}}/auth/signin
Content-Type: application/json

{
"clientToken":"{{clientToken}}",
  "sessionId": "{{sessionId}}"
}


### Me
GET {{u}}/users/me

####  update my profile
#PATCH {{u}}/users
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiaGlyb0BnbWFpbC5jb20iLCJpYXQiOjE2ODg5Njk3NzQsImV4cCI6MTY4ODk3MzM3NH0.wiYwslhhjB9hZBeTnmArTXybNmVhr4IEtaPp7Bs2A5Q
#
#{
#  "firstName": "Tadashi",
#  "lastName": "Hamada"
#}
#
#### Users: Delete
#DELETE {{u}}/users
