/*
  Warnings:

  - You are about to drop the column `audience` on the `courses` table. All the data in the column will be lost.
  - You are about to drop the column `duration_in_hours` on the `courses` table. All the data in the column will be lost.
  - You are about to drop the column `duration_lesson_in_minutes` on the `courses` table. All the data in the column will be lost.
  - Added the required column `audienceId` to the `courses` table without a default value. This is not possible if the table is not empty.
  - Added the required column `duration` to the `courses` table without a default value. This is not possible if the table is not empty.
  - Added the required column `durationLesson` to the `courses` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "courses" DROP COLUMN "audience";
ALTER TABLE "courses" DROP COLUMN "duration_in_hours";
ALTER TABLE "courses" DROP COLUMN "duration_lesson_in_minutes";
ALTER TABLE "courses" ADD COLUMN     "audienceId" INT4 NOT NULL;
ALTER TABLE "courses" ADD COLUMN     "duration" INT4 NOT NULL;
ALTER TABLE "courses" ADD COLUMN     "durationLesson" INT4 NOT NULL;

-- CreateTable
CREATE TABLE "audiences" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ageStart" INT4 NOT NULL,
    "ageEnd" INT4 NOT NULL,
    "level" STRING NOT NULL,

    CONSTRAINT "audiences_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "courses" ADD CONSTRAINT "courses_audienceId_fkey" FOREIGN KEY ("audienceId") REFERENCES "audiences"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
